id: 59eff382842944a3b5097e2824130b4e
initial_creation_type: ocr
source_metadata:
  volumes:
    29973ce257714ccc95817997d2534323:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ཡན་ལག་གི་ཉེས་པ་བདུན་པ།
      total_pages: 1953
      volume_number: 27
